Complete get endpoint, needs testing <3
dajwilson/task-api pull request #1
Opened 2024-01-22 15:07 UTC by dajwilson

2024-01-22 15:19 UTC, bethanlawx requested changes
proud of you <3

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/TaskApiApplication.java
> +import org.springframework.boot.SpringApplication;
unused

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/controller/TaskController.java
> +import com.tasks.taskapi.repository.TaskRepository;
unused

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/controller/TaskController.java
> +       List<Task> books =  taskService.getAllTasks();
variable name should be tasks

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/model/Task.java
> +    private Boolean inprogress;
probably don't need in progress and incomplete ? An enum could be good here xx

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/repository/TaskRepository.java
> +import org.springframework.boot.CommandLineRunner;
is this used ?

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/repository/TaskRepository.java
> +import org.springframework.boot.SpringApplication;
same here

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/repository/TaskRepository.java
> +import org.springframework.boot.autoconfigure.SpringBootApplication;
same here

2024-01-22 15:19 UTC, bethanlawx commented on src/main/java/com/tasks/taskapi/service/TaskService.java
> +import org.springframework.stereotype.Controller;
unused

2024-01-22 15:19 UTC, bethanlawx commented on src/main/resources/data.sql
> +INSERT INTO Tasks (id, name, priority, inprogress, incomplete) VALUES (1, 'Sleep', 3, false, false);
this can be simplified I think you only need INSERT INTO once

2024-01-22 15:19 UTC, bethanlawx commented on src/main/resources/schema.sql
> +Create Table Tasks (
capitalise create table ?

2024-01-22 15:19 UTC, bethanlawx commented on src/test/java/com/tasks/taskapi/TaskApiApplicationTests.java
> +class TaskApiApplicationTests {
was this autogenerated ?

2024-01-26 10:50 UTC, dajwilson commented on src/main/java/com/tasks/taskapi/TaskApiApplication.java
> +import org.springframework.boot.SpringApplication;
you are wrong

2024-01-26 14:35 UTC, bethanlawx approved these changes

2024-01-26 14:41 UTC, merged